version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password1'
      PGHOST: "db"
      PGUSER: "postgres"
      PGDBNAME: "findr"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" 
    volumes:
      - .:/findr
    ports: 
      - "3000:3000"
    depends_on:
      - db
    dns:
      - 1.1.1.1
      - 1.0.0.1
