default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: localhost

development:
  <<: *default
  database: findr_development
test:
  <<: *default
  database: findr_test

production:
  <<: *default
  database: findr_production
  username: findr
  password: <%= ENV['FINDR_DATABASE_PASSWORD'] %>
